site_name: Pixel-It Documentation
site_url: https://3bbaas.github.io/Pixel-It/
repo_name: 'Pixel-It'
repo_url: 'https://github.com/3bbaas/Pixel-It'

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: custom
      accent: custom
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: custom
      accent: custom
  features:
    - content.code.copy
    - navigation.footer
    - navigation.expand
    - navigation.instant

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Features:
      - Filters:
          - Negative: Filters/Negative.md
  - About: About.md


plugins:
  - search
  - tags
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
copyright: Copyright &copy; 2025 Pixel-It
