site_name: Pixel-It Documentation
site_url: https://3bbaas.github.io/Pixel-It/
repo_name: 'Pixel-It'
repo_url: 'https://github.com/3bbaas/Pixel-It'

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: custom
      accent: custom
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: custom
      accent: custom
  features:
    - content.code.copy
    - navigation.footer
    - navigation.expand
    - navigation.instant
    - navigation.path
    - navigation.top

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - Features:
      - Filters: 
          - Negative: Filters/negative.md
          - Blur: Filters/blur.md
          - Brightness: Filters/brightness.md
          - Contrast: Filters/contrast.md
          - Gamma: Filters/gamma.md
          - Gaussian Blur: Filters/gaussian_blur.md
          - Oil Painting: Filters/oil_painting.md
          - Sobel Edge: Filters/sobel.md
      - View: 
          - Channels: View/colors.md
          - Histogram: View/histogram.md
          - Image Equalization: View/equalized_image.md
  - About: About.md

plugins:
  - tags
  - git-authors
  - mkdocs-video:
      css_style:
      video_controls: false
      video_muted: true
      video_autoplay: true
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
  - search:
      lang: en

copyright: Copyright &copy; 2025 Pixel-It
